/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function renderAsync(svg: string | Buffer, options?: string | undefined | null, signal?: AbortSignal | undefined | null): Promise<RenderedImage>
export class Resvg {
  /** Get the SVG width */
  get width(): number
  /** Get the SVG height */
  get height(): number
}
export class RenderedImage {
  /** Get the PNG Buffer */
  asPng(): Buffer
  /** Get the PNG width */
  get width(): number
  /** Get the PNG height */
  get height(): number
}
