/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function renderAsync(svg: string | Buffer, options?: string | undefined | null, signal?: AbortSignal | undefined | null): Promise<RenderedImage>
export class Resvg {
  constructor(svg: string | Buffer, options?: string | undefined | null)
  /** Renders an SVG in Node.js */
  render(): RenderedImage
  /** Output usvg-simplified SVG string */
  toString(): string
  /** Get the SVG width */
  get width(): number
  /** Get the SVG height */
  get height(): number
}
export class RenderedImage {
  /** Write the image data to Buffer */
  asPng(): Buffer
  /** Get the PNG width */
  get width(): number
  /** Get the PNG height */
  get height(): number
}
